version: 2.1

references:
  branch_filter: &branch_filter
      branches:
        ignore:
          - gh-pages

jobs:
  test:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - phoenix-components-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install Dependencies
          command: pnpm install
      - save_cache:
          key: phoenix-components-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Run Commit Linter
          # The commit hash since when the history is checked
          command: npx commitlint --from ecee82ff287af77f21a3f42b2b80a1d96124b1e3 --to HEAD
      - run:
          name: Run Code Linter
          command: pnpm lint
      - run:
          name: Run Tests
          command: pnpm test

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters: *branch_filter
