export const PhoenixIconsOutlined = [
	'actions',
	'add-circle',
	'android',
	'angled-arrow-left',
	'angled-arrow-right',
	'apple',
	'arrow-down',
	'arrow-left',
	'arrow-right',
	'arrow-up',
	'asterisk',
	'browser',
	'burger',
	'calendar',
	'camera',
	'check',
	'check-circle',
	'clock',
	'cog',
	'copy',
	'cross',
	'deposit',
	'document',
	'dots-handle-reorder',
	'download',
	'edit',
	'ellipsis',
	'email',
	'exclamation',
	'exit',
	'external',
	'filter',
	'forward-arrow',
	'gift',
	'history',
	'house',
	'id-card',
	'info-circle',
	'language',
	'list',
	'lock',
	'paper',
	'passport',
	'photo-user',
	'pin',
	'play-circle',
	'profile',
	'question-circle',
	'refresh',
	'revert',
	'scales',
	'search',
	'star',
	'stopwatch',
	'subtract-circle',
	'times-circle',
	'transfer',
	'trash',
	'upload',
	'windows',
	'withdrawal',
	'wrench'
] as const
export type PhoenixIconsOutlined = typeof PhoenixIconsOutlined[number]

export const PhoenixIconsColored = [
	'calendar-primary',
	'camera-primary',
	'email-primary',
	'exclamation-error',
	'exclamation-warning',
	'house-primary',
	'id-card-primary',
	'lock-primary',
	'lock-success',
	'paper-primary',
	'passport-primary',
	'photo-user-primary',
	'pin-primary',
	'trash-error'
] as const
export type PhoenixIconsColored = typeof PhoenixIconsColored[number]

export const PhoenixIcons = [
	...PhoenixIconsOutlined,
	...PhoenixIconsColored
] as const
export type PhoenixIcons = typeof PhoenixIcons[number]
