name: Tests
run-name: Tests

on:
  workflow_dispatch: {}
  workflow_call: {}
  #todo: add this to feature push/pull request workflow

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  lint:
    runs-on: ubuntu-22.04
    name: testsWha

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Setup PNPM cache
        uses: actions/cache@v4
        with:
          path: /home/runner/setup-pnpm/node_modules/.bin/store/v3
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: Run Commit Linter
        run: pnpm dlx commitlint --from ecee82ff287af77f21a3f42b2b80a1d96124b1e3 --to HEAD

      - name: Run Code Linter
        run: pnpm run lint
